AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  events:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-284ab0f58c084c96/72adad6144bec1910157b2b3d762f20e
      Handler: btas.handler.EventLambda
      Runtime: java11
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  artists:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-284ab0f58c084c96/72adad6144bec1910157b2b3d762f20e
      Handler: btas.handler.ArtistLambda
      Runtime: java11
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  funds:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-284ab0f58c084c96/72adad6144bec1910157b2b3d762f20e
      Handler: btas.handler.FundLambda
      Runtime: java11
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  merch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lambda-artifacts-284ab0f58c084c96/72adad6144bec1910157b2b3d762f20e
      Handler: btas.handler.MerchLambda
      Runtime: java11
      Description: Java function
      MemorySize: 2048
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambda_ReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
